creds:
    base_url: http://llamacpp:8082/v1
    api_key: "llamacpp"
config:
    prompt_type: base
    model: gemma-4-E2B-it-GGUF
    genres: personal.
    thinking: false
    temperature: 0.0
    max_tokens: 4096
